"""app/config/defaults.py — 配置默认值。

所有配置项的默认值集中管理，供：
- 空配置时生成默认配置
- 配置迁移
- 测试
"""

from __future__ import annotations

# ---- API 默认值 ----
DEFAULT_BASE_URL = "https://api.openai.com/v1"
DEFAULT_MODEL = "gpt-4.1-mini"
DEFAULT_API_TIMEOUT_SECONDS = 60
DEFAULT_PROFILE_ID = "default"
DEFAULT_PROFILE_ALIAS = "默认"
DEFAULT_TEXT_MODEL = ""

# ---- 本地 LLM（Ollama 等 OpenAI 兼容端点）----
DEFAULT_LOCAL_LLM_BASE_URL = "http://127.0.0.1:11434/v1"
DEFAULT_LOCAL_LLM_API_KEY = "ollama"
DEFAULT_LOCAL_LLM_TIMEOUT_SECONDS = 120
# 未在目标硬件验证前，视觉/后台任务默认走云端，不自动切本地。
DEFAULT_LOCAL_LLM_VISION_ROUTE = "cloud"

# ---- TTS 默认值 ----
DEFAULT_TTS_ENABLED = False
DEFAULT_TTS_PROVIDER = "none"
DEFAULT_GPT_SOVITS_API_URL = "http://127.0.0.1:9880/tts"
DEFAULT_GPT_SOVITS_REF_LANG = "ja"
DEFAULT_GPT_SOVITS_TEXT_LANG = "ja"
DEFAULT_GPT_SOVITS_TIMEOUT_SECONDS = 60

# ---- 主动屏幕感知默认值 ----
DEFAULT_SCREEN_AWARENESS_ENABLED = True
DEFAULT_SCREEN_AWARENESS_SCREEN_CONTEXT_ENABLED = True
DEFAULT_SCREEN_AWARENESS_CHECK_INTERVAL_MINUTES = 20
DEFAULT_SCREEN_AWARENESS_COOLDOWN_MINUTES = 10
DEFAULT_SCREEN_AWARENESS_SCREEN_CONTEXT_BATCH_LIMIT = 6

# 兼容旧常量名；新代码请使用 DEFAULT_SCREEN_AWARENESS_*。
DEFAULT_PROACTIVE_CARE_ENABLED = DEFAULT_SCREEN_AWARENESS_ENABLED
DEFAULT_PROACTIVE_SCREEN_CONTEXT_ENABLED = DEFAULT_SCREEN_AWARENESS_SCREEN_CONTEXT_ENABLED
DEFAULT_PROACTIVE_CHECK_INTERVAL_MINUTES = DEFAULT_SCREEN_AWARENESS_CHECK_INTERVAL_MINUTES
DEFAULT_PROACTIVE_COOLDOWN_MINUTES = DEFAULT_SCREEN_AWARENESS_COOLDOWN_MINUTES
DEFAULT_PROACTIVE_SCREEN_CONTEXT_BATCH_LIMIT = DEFAULT_SCREEN_AWARENESS_SCREEN_CONTEXT_BATCH_LIMIT

# ---- 记忆整理默认值 ----
DEFAULT_MEMORY_CURATION_ENABLED = True
DEFAULT_MEMORY_CURATION_BACKFILL_LIMIT = 200
# 兼容旧配置：trigger_turns 仅作迁移；新逻辑以静默触发为主。
DEFAULT_MEMORY_CURATION_TRIGGER_TURNS = 8
DEFAULT_MEMORY_CURATION_IDLE_MINUTES = 12
DEFAULT_MEMORY_CURATION_MIN_TURNS = 2
DEFAULT_MEMORY_CURATION_COOLDOWN_MINUTES = 25
DEFAULT_MEMORY_CURATION_LONG_IDLE_MINUTES = 30
DEFAULT_MEMORY_CURATION_CATCH_UP_TURNS = 12

# ---- MCP 默认值 ----
DEFAULT_WINDOWS_MCP_ENABLED = False

# ---- 调试默认值 ----
DEFAULT_DEBUG_ENABLED = False
DEFAULT_DEBUG_BODY_ENABLED = False

# ---- UI 默认值 ----
DEFAULT_SUBTITLE_LANGUAGE = "zh"
DEFAULT_PORTRAIT_SCALE_PERCENT = 100
DEFAULT_PORTRAIT_SCALE_MIN = 50
DEFAULT_PORTRAIT_SCALE_MAX = 150
DEFAULT_FREE_ACCESS_ENABLED = True
# 字体大小
DEFAULT_SPEECH_FONT_SIZE = 19
SPEECH_FONT_SIZE_MIN = 10
SPEECH_FONT_SIZE_MAX = 24
DEFAULT_NAME_FONT_SIZE = 13
NAME_FONT_SIZE_MIN = 10
NAME_FONT_SIZE_MAX = 20
DEFAULT_INPUT_FONT_SIZE = 15
INPUT_FONT_SIZE_MIN = 12
INPUT_FONT_SIZE_MAX = 20
DEFAULT_BUTTON_FONT_SIZE = 15
BUTTON_FONT_SIZE_MIN = 12
BUTTON_FONT_SIZE_MAX = 20

# ---- 角色默认值 ----
DEFAULT_CHARACTER_ID = "sakura"
